"""changing user_info pk to user_id

Revision ID: 2fe7d0e6c141
Revises: d4fec24b8abb
Create Date: 2025-02-23 23:02:23.219496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe7d0e6c141'
down_revision: Union[str, None] = 'd4fec24b8abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'user_info_id', schema='access_control')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('user_info_id', sa.UUID(), autoincrement=False, nullable=False), schema='access_control')
    # ### end Alembic commands ###
