"""Changing ActivityAssignees PK

Revision ID: 2fe832711654
Revises: 4bdb0f8a3ba9
Create Date: 2025-04-03 23:33:41.867402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe832711654'
down_revision: Union[str, None] = '4bdb0f8a3ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_assignees', 'activity_assignee_id', schema='workflow')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_assignees', sa.Column('activity_assignee_id', sa.INTEGER(), autoincrement=True, nullable=False), schema='workflow')
    # ### end Alembic commands ###
