"""form_pattern, nullable form_field_id

Revision ID: 39fcce6e7c3c
Revises: ae911d837a00
Create Date: 2025-05-22 23:04:22.281280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39fcce6e7c3c'
down_revision: Union[str, None] = 'ae911d837a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_pattern', 'form_field_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='workflow')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_pattern', 'form_field_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='workflow')
    # ### end Alembic commands ###
