"""added form_field, input_type_enum, form_option, modified form_pattern

Revision ID: 693c9cb1da72
Revises: b93c1e69a76c
Create Date: 2025-05-22 22:06:35.457028

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "693c9cb1da72"
down_revision: Union[str, None] = "b93c1e69a76c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_field",
        sa.Column("form_field_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "input_type",
            sa.Enum(
                "section",
                "short_text",
                "long_text",
                "single_choice",
                "multiple_choice",
                "file_upload",
                name="input_type_enum",
                schema="workflow",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("next_field_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["next_field_id"],
            ["workflow.form_field.form_field_id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("form_field_id"),
        schema="workflow",
    )
    op.create_table(
        "field_option",
        sa.Column("field_option_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("form_field_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_field_id"], ["workflow.form_field.form_field_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("field_option_id"),
        schema="workflow",
    )
    op.add_column(
        "form_pattern",
        sa.Column("form_field_id", sa.Integer(), nullable=False),
        schema="workflow",
    )
    op.create_foreign_key(
        "fk_form_pattern_form_field_id",
        "form_pattern",
        "form_field",
        ["form_field_id"],
        ["form_field_id"],
        source_schema="workflow",
        referent_schema="workflow",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_form_pattern_form_field_id",
        "form_pattern",
        schema="workflow",
        type_="foreignkey",
    )
    op.drop_column("form_pattern", "form_field_id", schema="workflow")
    op.drop_table("field_option", schema="workflow")
    op.drop_table("form_field", schema="workflow")
    # ### end Alembic commands ###
