"""added order to field_option

Revision ID: ae911d837a00
Revises: 693c9cb1da72
Create Date: 2025-05-22 22:53:53.163814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae911d837a00'
down_revision: Union[str, None] = '693c9cb1da72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_option', sa.Column('option_order', sa.Integer(), nullable=False), schema='workflow')
    op.create_index(op.f('ix_workflow_field_option_option_order'), 'field_option', ['option_order'], unique=True, schema='workflow')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_field_option_option_order'), table_name='field_option', schema='workflow')
    op.drop_column('field_option', 'option_order', schema='workflow')
    # ### end Alembic commands ###
