"""added activity_field_display and modified publish on activity and form_pattern

Revision ID: cff45632bdd3
Revises: 39fcce6e7c3c
Create Date: 2025-05-26 21:26:17.125594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff45632bdd3'
down_revision: Union[str, None] = '39fcce6e7c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_field_display',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('form_field_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('activity_id', 'form_field_id'),
    schema='workflow'
    )
    op.add_column('form_pattern', sa.Column('published_at', sa.DateTime(), nullable=True), schema='workflow')
    op.drop_column('request_pattern', 'is_published', schema='workflow')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_pattern', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='workflow')
    op.drop_column('form_pattern', 'published_at', schema='workflow')
    op.drop_table('activity_field_display', schema='workflow')
    # ### end Alembic commands ###
