"""feat: adding secure code model

Revision ID: d4fec24b8abb
Revises: d98c9ea0bbcc
Create Date: 2025-02-17 21:07:09.687686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fec24b8abb'
down_revision: Union[str, None] = 'd98c9ea0bbcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secure_code',
    sa.Column('secure_code_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('has_been_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['access_control.user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('secure_code_id'),
    schema='access_control'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secure_code', schema='access_control')
    # ### end Alembic commands ###
