"""on delete cascade on activity_field_display

Revision ID: e7bc2834b3a1
Revises: cff45632bdd3
Create Date: 2025-05-26 21:52:03.323858

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7bc2834b3a1"
down_revision: Union[str, None] = "cff45632bdd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_activity_field_display_form_field",
        "activity_field_display",
        "form_field",
        ["form_field_id"],
        ["form_field_id"],
        source_schema="workflow",
        referent_schema="workflow",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_activity_field_display_activity",
        "activity_field_display",
        "activity",
        ["activity_id"],
        ["activity_id"],
        source_schema="workflow",
        referent_schema="workflow",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_activity_field_display_form_field",
        "activity_field_display",
        schema="workflow",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_activity_field_display_activity",
        "activity_field_display",
        schema="workflow",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
